/****************************************************************************
 * Copyright (c) 2008-2010 Matthew Ballance and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Armond Paiva - initial implementation
 ****************************************************************************/

package net.sf.sveditor.core.docs.model;

import java.io.IOException;
import java.io.Writer;
import java.util.Collection;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import net.sf.sveditor.core.docs.DocTopicManager;
import net.sf.sveditor.core.docs.IDocTopicManager;

/**
 * Model representation of the documentation set.
 * Generated by a DocModelFactory.
 * <p><p>
 * The model is a set of DocFiles, one for each source file, each of
 * which contains a set of DocTopics. Each DocTopic may also have
 * a set of child DocTopics when the DocTopic represents a scope
 * item such as a class, module, or interface.
 * <p>
 * @see DocModelFactory
 */
public class DocModel {
	
	/**
	 * Mapping of each DocFile by path. Path
	 * is that of the of the associated source file in
	 * the SVDBIndex.
	 * @see DocFile
	 */
	private Map<String, DocFile> docFiles ;
	
	/**
	 * Manager for all the known symbols
	 * @see SymbolTable
	 */
	private SymbolTable fSymbolTable ;
	
	/**
	 * One DocIndex per topic mapped by topic type name
	 * @see DocIndex
	 */
	private Map<String, DocIndex> indexMap ;
	
	/**
	 * Manger of all known topics and keywords
	 * @see IDocTopicManager
	 */
	private IDocTopicManager docTopicManager ;
	
	public DocModel() {
		docFiles = new HashMap<String, DocFile>() ;
		docTopicManager = new DocTopicManager() ;
		indexMap = new HashMap<String, DocIndex>() ;
		fSymbolTable = new SymbolTable() ;
	}

	/**
	 * Adds a new docFile to the model
	 * 
	 * @param docFile
	 */
	public void addDocFile(DocFile docFile) {
		docFiles.put(docFile.getTitle(),docFile) ;
	}
	
	/**
	 * @param filePath
	 * @return
	 */
	public DocFile getDocFile(String filePath) {
		return docFiles.get(filePath) ;
	}
	
	public Set<String> getFileSet() {
		return docFiles.keySet() ;
	}
	
	public Collection<DocFile> getDocFiles() {
		return new HashSet<DocFile>(docFiles.values()) ;
	}
	
	public SymbolTable getSymbolTable() {
		return fSymbolTable ;
	}

	public DocIndex getTopicIndexMap(String topic) {
		if(indexMap.containsKey(topic)) {
			return indexMap.get(topic) ;
		} else {
			return null ;
		}
	}
	
	public  DocIndex getCreateTopicIndexMap(String topic) {
		DocIndex index ;
		index = getTopicIndexMap(topic) ;
		if(index == null) {
			index = new DocIndex(topic) ;
			indexMap.put(topic, index) ;
		}
		return index ;
	}

	public IDocTopicManager getDocTopics() {
		return docTopicManager ;
	}
	
	/**
	 * Dumps content of model to a text
	 * file in a human readable format for debug and testing
	 * purposes
	 * <p><p>
	 * @param fileWriter Where to write the dump to
	 * @throws IOException 
	 */
	public void dumpToFile(Writer writer) throws IOException {
		fSymbolTable.dumpSymbolsToFile(writer) ;
		
	}

}
