/* Generated By:JavaCC: Do not edit this line. SVParserConstants.java */
package net.sf.sveditor.core.parser2;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SVParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EQ_3 = 6;
  /** RegularExpression Id. */
  int EQ_2 = 7;
  /** RegularExpression Id. */
  int EQ_1 = 8;
  /** RegularExpression Id. */
  int NE_1 = 9;
  /** RegularExpression Id. */
  int NE_2 = 10;
  /** RegularExpression Id. */
  int LSE = 11;
  /** RegularExpression Id. */
  int LLSE = 12;
  /** RegularExpression Id. */
  int LLS = 13;
  /** RegularExpression Id. */
  int RLS = 14;
  /** RegularExpression Id. */
  int LS = 15;
  /** RegularExpression Id. */
  int RS = 16;
  /** RegularExpression Id. */
  int LE = 17;
  /** RegularExpression Id. */
  int GE = 18;
  /** RegularExpression Id. */
  int LT = 19;
  /** RegularExpression Id. */
  int GT = 20;
  /** RegularExpression Id. */
  int LPAREN = 21;
  /** RegularExpression Id. */
  int RPAREN = 22;
  /** RegularExpression Id. */
  int ALIAS = 23;
  /** RegularExpression Id. */
  int ALWAYS = 24;
  /** RegularExpression Id. */
  int ALWAYS_COMB = 25;
  /** RegularExpression Id. */
  int ALWAYS_FF = 26;
  /** RegularExpression Id. */
  int ALWAYS_LATCH = 27;
  /** RegularExpression Id. */
  int AND = 28;
  /** RegularExpression Id. */
  int ASSERT = 29;
  /** RegularExpression Id. */
  int ASSIGN = 30;
  /** RegularExpression Id. */
  int ASSUME = 31;
  /** RegularExpression Id. */
  int AUTOMATIC = 32;
  /** RegularExpression Id. */
  int BEFORE = 33;
  /** RegularExpression Id. */
  int BEGIN = 34;
  /** RegularExpression Id. */
  int BIND = 35;
  /** RegularExpression Id. */
  int BINS = 36;
  /** RegularExpression Id. */
  int BINSOF = 37;
  /** RegularExpression Id. */
  int BIT = 38;
  /** RegularExpression Id. */
  int BREAK = 39;
  /** RegularExpression Id. */
  int BUF = 40;
  /** RegularExpression Id. */
  int BUFIF0 = 41;
  /** RegularExpression Id. */
  int BUFIF1 = 42;
  /** RegularExpression Id. */
  int BYTE = 43;
  /** RegularExpression Id. */
  int CASE = 44;
  /** RegularExpression Id. */
  int CASEX = 45;
  /** RegularExpression Id. */
  int CASEZ = 46;
  /** RegularExpression Id. */
  int CELL = 47;
  /** RegularExpression Id. */
  int CHANDLE = 48;
  /** RegularExpression Id. */
  int CLASS = 49;
  /** RegularExpression Id. */
  int CLOCKING = 50;
  /** RegularExpression Id. */
  int CMOS = 51;
  /** RegularExpression Id. */
  int CONFIG = 52;
  /** RegularExpression Id. */
  int CONST = 53;
  /** RegularExpression Id. */
  int CONSTRAINT = 54;
  /** RegularExpression Id. */
  int CONTEXT = 55;
  /** RegularExpression Id. */
  int CONTINUE = 56;
  /** RegularExpression Id. */
  int COVER = 57;
  /** RegularExpression Id. */
  int COVERGROUP = 58;
  /** RegularExpression Id. */
  int COVERPOINT = 59;
  /** RegularExpression Id. */
  int CROSS = 60;
  /** RegularExpression Id. */
  int DEASSIGN = 61;
  /** RegularExpression Id. */
  int T_DEFAULT = 62;
  /** RegularExpression Id. */
  int DEFPARAM = 63;
  /** RegularExpression Id. */
  int DESIGN = 64;
  /** RegularExpression Id. */
  int DISABLE = 65;
  /** RegularExpression Id. */
  int DIST = 66;
  /** RegularExpression Id. */
  int DO = 67;
  /** RegularExpression Id. */
  int EDGE = 68;
  /** RegularExpression Id. */
  int ELSE = 69;
  /** RegularExpression Id. */
  int END = 70;
  /** RegularExpression Id. */
  int ENDCASE = 71;
  /** RegularExpression Id. */
  int ENDCLASS = 72;
  /** RegularExpression Id. */
  int ENDCLOCKING = 73;
  /** RegularExpression Id. */
  int ENDCONFIG = 74;
  /** RegularExpression Id. */
  int ENDFUNCTION = 75;
  /** RegularExpression Id. */
  int ENDGENERATE = 76;
  /** RegularExpression Id. */
  int ENDGROUP = 77;
  /** RegularExpression Id. */
  int ENDINTERFACE = 78;
  /** RegularExpression Id. */
  int ENDMODULE = 79;
  /** RegularExpression Id. */
  int ENDPACKAGE = 80;
  /** RegularExpression Id. */
  int ENDPRIMITIVE = 81;
  /** RegularExpression Id. */
  int ENDPROGRAM = 82;
  /** RegularExpression Id. */
  int ENDPROPERTY = 83;
  /** RegularExpression Id. */
  int ENDSPECIFY = 84;
  /** RegularExpression Id. */
  int ENDSEQUENCE = 85;
  /** RegularExpression Id. */
  int ENDTABLE = 86;
  /** RegularExpression Id. */
  int ENDTASK = 87;
  /** RegularExpression Id. */
  int ENUM = 88;
  /** RegularExpression Id. */
  int EVENT = 89;
  /** RegularExpression Id. */
  int EXPECT = 90;
  /** RegularExpression Id. */
  int EXPORT = 91;
  /** RegularExpression Id. */
  int EXTENDS = 92;
  /** RegularExpression Id. */
  int EXTERN = 93;
  /** RegularExpression Id. */
  int FINAL = 94;
  /** RegularExpression Id. */
  int FIRST_MATCH = 95;
  /** RegularExpression Id. */
  int FOR = 96;
  /** RegularExpression Id. */
  int FORCE = 97;
  /** RegularExpression Id. */
  int FOREACH = 98;
  /** RegularExpression Id. */
  int FOREVER = 99;
  /** RegularExpression Id. */
  int FORK = 100;
  /** RegularExpression Id. */
  int FORKJOIN = 101;
  /** RegularExpression Id. */
  int FUNCTION = 102;
  /** RegularExpression Id. */
  int GENERATE = 103;
  /** RegularExpression Id. */
  int GENVAR = 104;
  /** RegularExpression Id. */
  int HIGHZ0 = 105;
  /** RegularExpression Id. */
  int HIGHZ1 = 106;
  /** RegularExpression Id. */
  int IF = 107;
  /** RegularExpression Id. */
  int IFF = 108;
  /** RegularExpression Id. */
  int IFNONE = 109;
  /** RegularExpression Id. */
  int IGNORE_BINS = 110;
  /** RegularExpression Id. */
  int ILLEGAL_BINS = 111;
  /** RegularExpression Id. */
  int IMPORT = 112;
  /** RegularExpression Id. */
  int INCDIR = 113;
  /** RegularExpression Id. */
  int INCLUDE = 114;
  /** RegularExpression Id. */
  int INITIAL = 115;
  /** RegularExpression Id. */
  int INOUT = 116;
  /** RegularExpression Id. */
  int INPUT = 117;
  /** RegularExpression Id. */
  int INSIDE = 118;
  /** RegularExpression Id. */
  int INSTANCE = 119;
  /** RegularExpression Id. */
  int INT = 120;
  /** RegularExpression Id. */
  int INTEGER = 121;
  /** RegularExpression Id. */
  int INTERFACE = 122;
  /** RegularExpression Id. */
  int INTERSECT = 123;
  /** RegularExpression Id. */
  int JOIN = 124;
  /** RegularExpression Id. */
  int JOIN_ANY = 125;
  /** RegularExpression Id. */
  int JOIN_NONE = 126;
  /** RegularExpression Id. */
  int LARGE = 127;
  /** RegularExpression Id. */
  int LIBLIST = 128;
  /** RegularExpression Id. */
  int LIBRARY = 129;
  /** RegularExpression Id. */
  int LOCAL = 130;
  /** RegularExpression Id. */
  int LOCALPARAM = 131;
  /** RegularExpression Id. */
  int LOGIC = 132;
  /** RegularExpression Id. */
  int LONGINT = 133;
  /** RegularExpression Id. */
  int MACROMODULE = 134;
  /** RegularExpression Id. */
  int MATCHES = 135;
  /** RegularExpression Id. */
  int MEDIUM = 136;
  /** RegularExpression Id. */
  int MODPORT = 137;
  /** RegularExpression Id. */
  int MODULE = 138;
  /** RegularExpression Id. */
  int NAND = 139;
  /** RegularExpression Id. */
  int NEGEDGE = 140;
  /** RegularExpression Id. */
  int NEW = 141;
  /** RegularExpression Id. */
  int NMOS = 142;
  /** RegularExpression Id. */
  int NOR = 143;
  /** RegularExpression Id. */
  int NOSHOWCANCELLED = 144;
  /** RegularExpression Id. */
  int NOT = 145;
  /** RegularExpression Id. */
  int NOTIF0 = 146;
  /** RegularExpression Id. */
  int NOTIF1 = 147;
  /** RegularExpression Id. */
  int NULL = 148;
  /** RegularExpression Id. */
  int OPTION = 149;
  /** RegularExpression Id. */
  int OR = 150;
  /** RegularExpression Id. */
  int OUTPUT = 151;
  /** RegularExpression Id. */
  int PACKAGE = 152;
  /** RegularExpression Id. */
  int PACKED = 153;
  /** RegularExpression Id. */
  int PARAMETER = 154;
  /** RegularExpression Id. */
  int PMOS = 155;
  /** RegularExpression Id. */
  int POSEDGE = 156;
  /** RegularExpression Id. */
  int PRIMITIVE = 157;
  /** RegularExpression Id. */
  int PRIORITY = 158;
  /** RegularExpression Id. */
  int PROGRAM = 159;
  /** RegularExpression Id. */
  int PROPERTY = 160;
  /** RegularExpression Id. */
  int PROTECTED = 161;
  /** RegularExpression Id. */
  int PULL0 = 162;
  /** RegularExpression Id. */
  int PULL1 = 163;
  /** RegularExpression Id. */
  int PULLDOWN = 164;
  /** RegularExpression Id. */
  int PULLUP = 165;
  /** RegularExpression Id. */
  int PULSESTYLE_ONEVENT = 166;
  /** RegularExpression Id. */
  int PULSESTYLE_ONDETECT = 167;
  /** RegularExpression Id. */
  int PURE = 168;
  /** RegularExpression Id. */
  int RAND = 169;
  /** RegularExpression Id. */
  int RANDC = 170;
  /** RegularExpression Id. */
  int RANDCASE = 171;
  /** RegularExpression Id. */
  int RANDSEQUENCE = 172;
  /** RegularExpression Id. */
  int RCMOS = 173;
  /** RegularExpression Id. */
  int REAL = 174;
  /** RegularExpression Id. */
  int REALTIME = 175;
  /** RegularExpression Id. */
  int REF = 176;
  /** RegularExpression Id. */
  int REG = 177;
  /** RegularExpression Id. */
  int RELEASE = 178;
  /** RegularExpression Id. */
  int REPEAT = 179;
  /** RegularExpression Id. */
  int RETURN = 180;
  /** RegularExpression Id. */
  int RNMOS = 181;
  /** RegularExpression Id. */
  int RPMOS = 182;
  /** RegularExpression Id. */
  int RTRAN = 183;
  /** RegularExpression Id. */
  int RTRANIF0 = 184;
  /** RegularExpression Id. */
  int RTRANIF1 = 185;
  /** RegularExpression Id. */
  int SCALARED = 186;
  /** RegularExpression Id. */
  int SEQUENCE = 187;
  /** RegularExpression Id. */
  int SHORTINT = 188;
  /** RegularExpression Id. */
  int SHORTREAL = 189;
  /** RegularExpression Id. */
  int SHOWCANCELLED = 190;
  /** RegularExpression Id. */
  int SIGNED = 191;
  /** RegularExpression Id. */
  int SMALL = 192;
  /** RegularExpression Id. */
  int SOLVE = 193;
  /** RegularExpression Id. */
  int SPECIFY = 194;
  /** RegularExpression Id. */
  int SPECPARAM = 195;
  /** RegularExpression Id. */
  int STATIC = 196;
  /** RegularExpression Id. */
  int STRING = 197;
  /** RegularExpression Id. */
  int STRONG0 = 198;
  /** RegularExpression Id. */
  int STRONG1 = 199;
  /** RegularExpression Id. */
  int STRUCT = 200;
  /** RegularExpression Id. */
  int SUPER = 201;
  /** RegularExpression Id. */
  int SUPPLY0 = 202;
  /** RegularExpression Id. */
  int SUPPLY1 = 203;
  /** RegularExpression Id. */
  int TABLE = 204;
  /** RegularExpression Id. */
  int TAGGED = 205;
  /** RegularExpression Id. */
  int TASK = 206;
  /** RegularExpression Id. */
  int THIS = 207;
  /** RegularExpression Id. */
  int THROUGHOUT = 208;
  /** RegularExpression Id. */
  int TIME = 209;
  /** RegularExpression Id. */
  int TIMEPRECISION = 210;
  /** RegularExpression Id. */
  int TIMEUNIT = 211;
  /** RegularExpression Id. */
  int TRAN = 212;
  /** RegularExpression Id. */
  int TRANIF0 = 213;
  /** RegularExpression Id. */
  int TRANIF1 = 214;
  /** RegularExpression Id. */
  int TRI = 215;
  /** RegularExpression Id. */
  int TRI0 = 216;
  /** RegularExpression Id. */
  int TRI1 = 217;
  /** RegularExpression Id. */
  int TRIAND = 218;
  /** RegularExpression Id. */
  int TRIOR = 219;
  /** RegularExpression Id. */
  int TRIREG = 220;
  /** RegularExpression Id. */
  int TYPE = 221;
  /** RegularExpression Id. */
  int TYPE_OPTION = 222;
  /** RegularExpression Id. */
  int TYPEDEF = 223;
  /** RegularExpression Id. */
  int UNION = 224;
  /** RegularExpression Id. */
  int UNIQUE = 225;
  /** RegularExpression Id. */
  int UNSIGNED = 226;
  /** RegularExpression Id. */
  int USE = 227;
  /** RegularExpression Id. */
  int UWIRE = 228;
  /** RegularExpression Id. */
  int VAR = 229;
  /** RegularExpression Id. */
  int VECTORED = 230;
  /** RegularExpression Id. */
  int VIRTUAL = 231;
  /** RegularExpression Id. */
  int VOID = 232;
  /** RegularExpression Id. */
  int WAIT = 233;
  /** RegularExpression Id. */
  int WAIT_ORDER = 234;
  /** RegularExpression Id. */
  int WAND = 235;
  /** RegularExpression Id. */
  int WEAK0 = 236;
  /** RegularExpression Id. */
  int WEAK1 = 237;
  /** RegularExpression Id. */
  int WHILE = 238;
  /** RegularExpression Id. */
  int WILDCARD = 239;
  /** RegularExpression Id. */
  int WIRE = 240;
  /** RegularExpression Id. */
  int WITH = 241;
  /** RegularExpression Id. */
  int WITHIN = 242;
  /** RegularExpression Id. */
  int WOR = 243;
  /** RegularExpression Id. */
  int XNOR = 244;
  /** RegularExpression Id. */
  int XOR = 245;
  /** RegularExpression Id. */
  int PATHPULSE = 246;
  /** RegularExpression Id. */
  int RANDOMIZE = 247;
  /** RegularExpression Id. */
  int SEMICOLON = 248;
  /** RegularExpression Id. */
  int TS_S = 249;
  /** RegularExpression Id. */
  int TS_MS = 250;
  /** RegularExpression Id. */
  int TS_US = 251;
  /** RegularExpression Id. */
  int TS_NS = 252;
  /** RegularExpression Id. */
  int TS_PS = 253;
  /** RegularExpression Id. */
  int TS_FS = 254;
  /** RegularExpression Id. */
  int TS_STEP = 255;
  /** RegularExpression Id. */
  int DPI = 256;
  /** RegularExpression Id. */
  int DPI_C = 257;
  /** RegularExpression Id. */
  int TF_IDENT = 258;
  /** RegularExpression Id. */
  int S_IDENT = 259;
  /** RegularExpression Id. */
  int C_IDENT = 260;
  /** RegularExpression Id. */
  int ATTR_START = 261;
  /** RegularExpression Id. */
  int ATTR_END = 262;
  /** RegularExpression Id. */
  int ESCAPE = 263;
  /** RegularExpression Id. */
  int STRING_LITERAL = 264;
  /** RegularExpression Id. */
  int DEC_DIGIT = 265;
  /** RegularExpression Id. */
  int NZ_DEC_DIGIT = 266;
  /** RegularExpression Id. */
  int HEX_DIGIT = 267;
  /** RegularExpression Id. */
  int OCT_DIGIT = 268;
  /** RegularExpression Id. */
  int BIN4S_DIGIT = 269;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"===\"",
    "\"==\"",
    "\"=\"",
    "\"!=\"",
    "\"!==\"",
    "\"<<=\"",
    "\"<<<=\"",
    "\"<<<\"",
    "\">>>\"",
    "\"<<\"",
    "\">>\"",
    "\"<=\"",
    "\">=\"",
    "\"<\"",
    "\">\"",
    "\"(\"",
    "\")\"",
    "\"alias\"",
    "\"always\"",
    "\"always_comb\"",
    "\"always_ff\"",
    "\"always_latch\"",
    "\"and\"",
    "\"assert\"",
    "\"assign\"",
    "\"assume\"",
    "\"automatic\"",
    "\"before\"",
    "\"begin\"",
    "\"bind\"",
    "\"bins\"",
    "\"binsof\"",
    "\"bit\"",
    "\"break\"",
    "\"buf\"",
    "\"bufif0\"",
    "\"bufif1\"",
    "\"byte\"",
    "\"case\"",
    "\"casex\"",
    "\"casez\"",
    "\"cell\"",
    "\"chandle\"",
    "\"class\"",
    "\"clocking\"",
    "\"cmos\"",
    "\"config\"",
    "\"const\"",
    "\"constraint\"",
    "\"context\"",
    "\"continue\"",
    "\"cover\"",
    "\"covergroup\"",
    "\"coverpoint\"",
    "\"cross\"",
    "\"deassign\"",
    "\"default\"",
    "\"defparam\"",
    "\"design\"",
    "\"disable\"",
    "\"dist\"",
    "\"do\"",
    "\"edge\"",
    "\"else\"",
    "\"end\"",
    "\"endcase\"",
    "\"endclass\"",
    "\"endclocking\"",
    "\"endconfig\"",
    "\"endfunction\"",
    "\"endgenerate\"",
    "\"endgroup\"",
    "\"endinterface\"",
    "\"endmodule\"",
    "\"endpackage\"",
    "\"endprimitive\"",
    "\"endprogram\"",
    "\"endproperty\"",
    "\"endspecify\"",
    "\"endsequence\"",
    "\"endtable\"",
    "\"endtask\"",
    "\"enum\"",
    "\"event\"",
    "\"expect\"",
    "\"export\"",
    "\"extends\"",
    "\"extern\"",
    "\"final\"",
    "\"first_match\"",
    "\"for\"",
    "\"force\"",
    "\"foreach\"",
    "\"forever\"",
    "\"fork\"",
    "\"forkjoin\"",
    "\"function\"",
    "\"generate\"",
    "\"genvar\"",
    "\"highz0\"",
    "\"highz1\"",
    "\"if\"",
    "\"iff\"",
    "\"ifnone\"",
    "\"ignore_bins\"",
    "\"illegal_bins\"",
    "\"import\"",
    "\"incdir\"",
    "\"include\"",
    "\"initial\"",
    "\"inout\"",
    "\"input\"",
    "\"inside\"",
    "\"instance\"",
    "\"int\"",
    "\"integer\"",
    "\"interface\"",
    "\"intersect\"",
    "\"join\"",
    "\"join_any\"",
    "\"join_none\"",
    "\"large\"",
    "\"liblist\"",
    "\"library\"",
    "\"local\"",
    "\"localparam\"",
    "\"logic\"",
    "\"longint\"",
    "\"macromodule\"",
    "\"matches\"",
    "\"medium\"",
    "\"modport\"",
    "\"module\"",
    "\"nand\"",
    "\"negedge\"",
    "\"new\"",
    "\"nmos\"",
    "\"nor\"",
    "\"noshowcancelled\"",
    "\"not\"",
    "\"notif0\"",
    "\"notif1\"",
    "\"null\"",
    "\"option\"",
    "\"or\"",
    "\"output\"",
    "\"package\"",
    "\"packed\"",
    "\"parameter\"",
    "\"pmos\"",
    "\"posedge\"",
    "\"primitive\"",
    "\"priority\"",
    "\"program\"",
    "\"property\"",
    "\"protected\"",
    "\"pull0\"",
    "\"pull1\"",
    "\"pulldown\"",
    "\"pullup\"",
    "\"pulsestyle_onevent\"",
    "\"pulsestyle_ondetect\"",
    "\"pure\"",
    "\"rand\"",
    "\"randc\"",
    "\"randcase\"",
    "\"randsequence\"",
    "\"rcmos\"",
    "\"real\"",
    "\"realtime\"",
    "\"ref\"",
    "\"reg\"",
    "\"release\"",
    "\"repeat\"",
    "\"return\"",
    "\"rnmos\"",
    "\"rpmos\"",
    "\"rtran\"",
    "\"rtranif0\"",
    "\"rtranif1\"",
    "\"scalared\"",
    "\"sequence\"",
    "\"shortint\"",
    "\"shortreal\"",
    "\"showcancelled\"",
    "\"signed\"",
    "\"small\"",
    "\"solve\"",
    "\"specify\"",
    "\"specparam\"",
    "\"static\"",
    "\"string\"",
    "\"strong0\"",
    "\"strong1\"",
    "\"struct\"",
    "\"super\"",
    "\"supply0\"",
    "\"supply1\"",
    "\"table\"",
    "\"tagged\"",
    "\"task\"",
    "\"this\"",
    "\"throughout\"",
    "\"time\"",
    "\"timeprecision\"",
    "\"timeunit\"",
    "\"tran\"",
    "\"tranif0\"",
    "\"tranif1\"",
    "\"tri\"",
    "\"tri0\"",
    "\"tri1\"",
    "\"triand\"",
    "\"trior\"",
    "\"trireg\"",
    "\"type\"",
    "\"type_option\"",
    "\"typedef\"",
    "\"union\"",
    "\"unique\"",
    "\"unsigned\"",
    "\"use\"",
    "\"uwire\"",
    "\"var\"",
    "\"vectored\"",
    "\"virtual\"",
    "\"void\"",
    "\"wait\"",
    "\"wait_order\"",
    "\"wand\"",
    "\"weak0\"",
    "\"weak1\"",
    "\"while\"",
    "\"wildcard\"",
    "\"wire\"",
    "\"with\"",
    "\"within\"",
    "\"wor\"",
    "\"xnor\"",
    "\"xor\"",
    "\"PATHPULSE$\"",
    "\"randomize\"",
    "\";\"",
    "\"s\"",
    "\"ms\"",
    "\"us\"",
    "\"ns\"",
    "\"ps\"",
    "\"fs\"",
    "\"step\"",
    "\"\\\"DPI\\\"\"",
    "\"\\\"DPI-C\\\"\"",
    "<TF_IDENT>",
    "<S_IDENT>",
    "<C_IDENT>",
    "\"(*\"",
    "\"*)\"",
    "\"\\\\\"",
    "<STRING_LITERAL>",
    "<DEC_DIGIT>",
    "<NZ_DEC_DIGIT>",
    "<HEX_DIGIT>",
    "<OCT_DIGIT>",
    "<BIN4S_DIGIT>",
    "\":\"",
    "\".*\"",
    "\"#\"",
    "\",\"",
    "\".\"",
    "\"{\"",
    "\"}\"",
    "\"\\u2013>\"",
    "\":=\"",
    "\":/\"",
    "\"::\"",
    "\"*\"",
    "\"[\"",
    "\"]\"",
    "\"$\"",
    "\"+\"",
    "\"++\"",
    "\"\\u2013\"",
    "\"\\u2013\\u2013\"",
    "\"**\"",
    "\"/\"",
    "\"%\"",
    "\"|->\"",
    "\"|=>\"",
    "\"##\"",
    "\"[*\"",
    "\"[=\"",
    "\"[->\"",
    "\"@@\"",
    "\"=>\"",
    "\"!\"",
    "\"&&\"",
    "\"||\"",
    "\"1\\u2019b0\"",
    "\"1\\u2019b1\"",
    "\"1\\u2019bx\"",
    "\"1\\u2019bX\"",
    "\"1\\u2019B0\"",
    "\"1\\u2019B1\"",
    "\"1\\u2019Bx\"",
    "\"1\\u2019BX\"",
    "\"1\"",
    "\"0\"",
    "\"-\"",
    "\"x\"",
    "\"X\"",
    "\"r\"",
    "\"R\"",
    "\"f\"",
    "\"F\"",
    "\"p\"",
    "\"P\"",
    "\"n\"",
    "\"N\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"@\"",
    "\"@*\"",
    "\"->\"",
    "\"->>\"",
    "\"&&&\"",
    "\"\\u2019{\"",
    "\"\\\'{\"",
    "\"\\\'\"",
    "\"|\"",
    "\"*>\"",
    "\"+:\"",
    "\"-:\"",
    "\"?\"",
    "\"~\"",
    "\"&\"",
    "\"~&\"",
    "\"~|\"",
    "\"^\"",
    "\"~^\"",
    "\"^~\"",
    "\"==?\"",
    "\"!=?\"",
    "\"--\"",
    "\"_\"",
    "\"e\"",
    "\"E\"",
    "\"\\u2019\"",
    "\"S\"",
    "\"d\"",
    "\"D\"",
    "\"b\"",
    "\"B\"",
    "\"o\"",
    "\"O\"",
    "\"h\"",
    "\"H\"",
    "\"z\"",
    "\"Z\"",
    "\"\\\'0\"",
    "\"\\\'1\"",
    "\"$root\"",
    "\"$unit\"",
  };

}
