 /***************************************************************************
 * Copyright (c) 2008-2011 Matthew Ballance and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Natural Docs - Initial contributor
 *     Armond Paiva - repurposed for use in SVEditor
 ****************************************************************************/

/*
   This file is part of Natural Docs, which is Copyright © 2003-2010 Greg Valure.
   Natural Docs is licensed under version 3 of the GNU Affero General Public
   License (AGPL).  Refer to License.txt for the complete details.

   This file may be distributed with documentation files generated by Natural Docs.
   Such documentation is not covered by Natural Docs' copyright and licensing,
   and may have its own copyright and distribution terms as decided by its author.
*/

var indexSectionsWithContent = {
   "General": {
      "Symbols": false,
      "Numbers": false,
      "A": false,
      "B": false,
      "C": true,
      "D": true,
      "E": false,
      "F": false,
      "G": true,
      "H": false,
      "I": true,
      "J": false,
      "K": false,
      "L": false,
      "M": false,
      "N": true,
      "O": false,
      "P": true,
      "Q": false,
      "R": true,
      "S": true,
      "T": false,
      "U": true,
      "V": false,
      "W": false,
      "X": false,
      "Y": false,
      "Z": false
      },
   "Variables": {
      "Symbols": false,
      "Numbers": false,
      "A": false,
      "B": false,
      "C": false,
      "D": false,
      "E": false,
      "F": false,
      "G": false,
      "H": false,
      "I": false,
      "J": false,
      "K": false,
      "L": false,
      "M": false,
      "N": false,
      "O": false,
      "P": false,
      "Q": false,
      "R": false,
      "S": false,
      "T": false,
      "U": true,
      "V": false,
      "W": false,
      "X": false,
      "Y": false,
      "Z": false
      },
   "Functions": {
      "Symbols": false,
      "Numbers": false,
      "A": false,
      "B": false,
      "C": true,
      "D": true,
      "E": false,
      "F": false,
      "G": true,
      "H": false,
      "I": false,
      "J": false,
      "K": false,
      "L": false,
      "M": false,
      "N": true,
      "O": false,
      "P": true,
      "Q": false,
      "R": true,
      "S": true,
      "T": false,
      "U": true,
      "V": false,
      "W": false,
      "X": false,
      "Y": false,
      "Z": false
      },
   "Classes": {
      "Symbols": false,
      "Numbers": false,
      "A": false,
      "B": false,
      "C": false,
      "D": false,
      "E": false,
      "F": false,
      "G": false,
      "H": false,
      "I": false,
      "J": false,
      "K": false,
      "L": false,
      "M": false,
      "N": false,
      "O": false,
      "P": false,
      "Q": false,
      "R": false,
      "S": false,
      "T": false,
      "U": true,
      "V": false,
      "W": false,
      "X": false,
      "Y": false,
      "Z": false
      }
   }
