
include $(SIMSCRIPTS_DIR)/mkfiles/plusargs.mk

TB=${name}_tb

# Must build DPI libraries
DPI_LIBRARIES += $(call get_plusarg,DPI_LIBRARY,$(PLUSARGS))

include $(SIMSCRIPTS_DIR)/mkfiles/common_sim.mk


	