#!/bin/sh
#****************************************************************************
#* ncvlog
#*
#* Wrapper for 'ncvlog' to allow arguments to be intercepted and collected
#* in a file
#****************************************************************************

if test "x$SVE_COMPILER_ARGS_FILE" = "x"; then
	echo "[ERROR] SVE_COMPILER_ARGS_FILE not set"
	exit 1
fi

CWD=`pwd`

echo "/**" >> $SVE_COMPILER_ARGS_FILE
echo " * Invoking ncvlog in $CWD" >> $SVE_COMPILER_ARGS_FILE
echo " * ncvlog $*" >> $SVE_COMPILER_ARGS_FILE
echo " */" >> $SVE_COMPILER_ARGS_FILE


while test -n "$1"; do
	case "$1" in
		*)
		if test -f "$1"; then
			# Convert this to a full path
			filedir=`dirname "$1"`
			filename=`basename "$1"`
			filedir=`cd $filedir ; pwd`
			echo "${filedir}/${filename}" >> $SVE_COMPILER_ARGS_FILE
		elif test -d "$1"; then
			# Convert this to a full path
			dir=`cd $dir; pwd`
			echo "${dir}" >> $SVE_COMPILER_ARGS_FILE
		else
			echo "$1" >> $SVE_COMPILER_ARGS_FILE
		fi
		;;
	esac
	shift
done

echo "" >> $SVE_COMPILER_ARGS_FILE
echo "" >> $SVE_COMPILER_ARGS_FILE
